/**
 * =============================================================================
 * AI SVG Generation API
 * =============================================================================
 *
 * Accepts a text prompt and returns an SVG string generated by GPT-4o-mini.
 * The SVG is designed for 3D extrusion: flat, single-color, black fills,
 * uses fill-rule="evenodd" so holes (e.g. inside letters) extrude correctly.
 *
 * Requires the OPENAI_API_KEY environment variable.
 */

import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const SYSTEM_PROMPT = `You are an expert SVG icon designer. When given a description, you generate a clean, minimal SVG optimized for 3D extrusion.

Rules:
- Output ONLY the raw SVG markup — no markdown, no code fences, no explanations.
- Use a square viewBox: viewBox="0 0 200 200"
- Set width="200" height="200" on the <svg> element.
- Use ONLY black fills: fill="black"
- Use fill-rule="evenodd" on all <path> elements so interior holes extrude correctly.
- No gradients, no strokes, no colors other than black, no transparency.
- Keep the design simple, bold, and recognizable — think app icon or logo silhouette.
- Center the shape within the viewBox with reasonable padding (~10px on each side).
- Prefer a single compound <path> or a small number of <path> elements.
- Do NOT include any <text> elements.`;

export async function POST(req: NextRequest) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "OPENAI_API_KEY is not configured" },
      { status: 503 }
    );
  }

  let prompt: string;
  try {
    const body = await req.json();
    prompt = (body.prompt ?? "").toString().trim();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  if (!prompt) {
    return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
  }

  if (prompt.length > 500) {
    return NextResponse.json(
      { error: "Prompt must be 500 characters or fewer" },
      { status: 400 }
    );
  }

  const openai = new OpenAI({ apiKey });

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      {
        role: "user",
        content: `Generate an SVG icon for: ${prompt}`,
      },
    ],
    max_tokens: 2048,
    temperature: 0.7,
  });

  const raw = completion.choices[0]?.message?.content ?? "";

  // Extract SVG — the model should return only SVG, but strip any accidental
  // markdown code fences just in case.
  const svgMatch = raw.match(/<svg[\s\S]*<\/svg>/i);
  const svg = svgMatch ? svgMatch[0] : raw.trim();

  if (!svg.startsWith("<svg")) {
    return NextResponse.json(
      { error: "AI did not return a valid SVG" },
      { status: 502 }
    );
  }

  return NextResponse.json({ svg });
}
